from abc import ABC, abstractmethod
from typing import List


class BaseEmbeddingService(ABC):
    """Abstract base class for embedding models."""

    @property
    @abstractmethod
    def dimension(self) -> int:
        """Return the dimension of embeddings generated by this service."""
        pass

    @abstractmethod
    def embed(self, text: str) -> List[float]:
        """Generate normalized embedding for a single text."""
        pass

    @abstractmethod
    def embed_many(self, texts: List[str]) -> List[List[float]]:
        """Generate normalized embeddings for multiple texts in batch."""
        pass
